# Generated by Django 6.0 on 2025-12-23 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='updated_at',
        ),
    ]
