# Generated by Django 6.0 on 2025-12-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_accounts_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière modification'),
        ),
    ]
