# Generated by Django 6.0 on 2025-12-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_accounts_created_at_accounts_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='role',
            field=models.CharField(choices=[('user', 'Utilisateur'), ('planner', 'Planificateur'), ('admin', 'Administrateur')], default='user', help_text="Rôle de l'utilisateur dans l'application", max_length=20, verbose_name='Rôle'),
        ),
    ]
